apiVersion: v1
kind: Service
metadata:
  name: apache-nginx-load-balance
  namespace: default
  labels:
    app: apache-nginx-load-balance
spec:
  selector:
    app: apache-nginx-load-balance
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-nginx-load-balance
  namespace: default
  labels:
    app: apache-nginx-load-balance
spec:
  selector:
    matchLabels:
      app: apache-nginx-load-balance
  replicas: 3
  template:
    metadata:
      labels:
        app: apache-nginx-load-balance
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /var/www/html
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        volumeMounts:
        - name: www-data
          mountPath: /usr/share/nginx/html
      volumes:
      - name: www-data
        emptyDir: {}