version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-password"
      MYSQL_CLUSTER_NAME: "my-cluster"
      MYSQL_USER: "my-user"
      MYSQL_PASSWORD: "my-password"
      MYSQL_DATABASE: "my-database"
    volumes:
      - ./.dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      labels:
        - "traefik.backend=mysql"
        - "traefik.enable=true"
        - "traefik.port=3306"
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
