version: "3.8"
services:
  mysql:
    image: mysql:8.0
    networks:
      - my-network
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      my-network:
        driver: bridge

volumes:
  mysql-db:
