version: '3.7'

networks:
  default:
    external: true
  apache-net:
    driver: bridge

services:
  # Apache web server
  apache:
    image: httpd:2.4
    container_name: apache
    hostname: apache
    restart: always
    networks:
      - apache-net
      - default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/var/www/html
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 3

  # MySQL database
  mysql:
    image: mysql:5.7
    container_name: mysql
    hostname: mysql
    restart: always
    networks:
      - apache-net
      - default
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

# Persistent volumes
volumes:
  mysql-data:
    driver: local