version: '3'

services:
  python:
    image: python:3.8-slim
    container_name: python
    networks:
      - app-network
    ports:
      - 5000:5000
    environment:
      FLASK_APP: app
      FLASK_DEBUG: 1
    volumes:
      - ./app:/app
    depends_on:
      - db

networks:
  app-network:
    driver: bridge