version: '3.8'

services:
  mysql-main:
    image: mysql:8.0
    container_name: mysql-main
    networks:
      - mysql-stack
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  mysql-slave-1:
    image: mysql:8.0
    container_name: mysql-slave-1
    networks:
      - mysql-stack
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
      - mysql-main

  mysql-slave-2:
    image: mysql:8.0
    container_name: mysql-slave-2
    networks:
      - mysql-stack
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    depends_on:
      - mysql-main

volumes:
  mysql-data:

networks:
  mysql-stack:
    driver: bridge