apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
  namespace: default
  labels:
    app: mysql-cluster
spec:
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    targetPort: mysql
  selector:
    app: mysql-cluster

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-cluster
  namespace: default
  labels:
    app: mysql-cluster
spec:
  serviceName: mysql-cluster
  replicas: 2
  selector:
    matchLabels:
      app: mysql-cluster
  template:
    metadata:
      labels:
        app: mysql-cluster
    spec:
      initContainers:
      - name: init-mysql-data
        image: mysql:latest
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        command: ["bash", "-c", "mysql_install_db"]
      containers:
      - name: mysql
        image: mysql:latest
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my-secret-password
        - name: MYSQL_DATABASE
          value: my-database
        - name: MYSQL_USER
          value: my-user
        - name: MYSQL_PASSWORD
          value: my-password
        ports:
        - containerPort: 3306
          name: mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data