apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster-svc
  namespace: default
  labels:
    app: nginx-cluster
spec:
  type: NodePort
  selector:
    app: nginx-cluster
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cluster
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx-cluster
  template:
    metadata:
      labels:
        app: nginx-cluster
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi