apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cluster
  labels:
    app: nginx-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-cluster
  template:
    metadata:
      labels:
        app: nginx-cluster
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 9999
        env:
        - name: NGINX_PORT
          value: "9999"
        - name: NGINX_WORKER_PROCESSES
          value: "4"

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-cluster
spec:
  type: NodePort
  selector:
    app: nginx-cluster
  ports:
  - port: 1988
    targetPort: 9999
    nodePort: 30080